'use strict';
const UI={
fr:{island:'Corse',kicker:'Notre voyage en famille',hero:'Des villages perchés aux criques turquoise, des citadelles aux montagnes. Nos idées pour découvrir la Corse à notre rythme, entre Calvi et Porto-Vecchio.',all:'Tout',beaches:'🏖️ Plages',culture:'🏛️ Culture',nature:'🌿 Nature',long:'🚗 Grandes excursions',mapTitle:'L’île, à portée de main',mapSub:'Touchez un lieu pour retrouver sa fiche. Zoomez pour distinguer les lieux proches. Les filtres s’appliquent à la carte et aux idées de sorties.',mapNote:'🏖️ Plages · 🏛️ Culture et patrimoine · 🌿 Nature. Les temps de route sont des estimations aller, hors pauses. Le bouton « Itinéraire » calcule le trajet depuis votre point de départ.',placesTitle:'À voir, à vivre, à partager',placesSub:'Choisissez selon l’envie du jour. Les grandes excursions demandent une journée dédiée ; les favoris restent enregistrés sur cet appareil.',favTitle:'❤️ Nos favoris',favEmpty:'Touchez ♡ sur une fiche pour préparer votre sélection.',footer:'En fin septembre et début octobre, adaptez les sorties à la météo et aux horaires de saison. Pour les bateaux, les routes de montagne et les rivières, consultez les informations locales avant de partir.',route:'🧭 Itinéraire',learn:'Découvrir ↗',advice:'💡 Notre conseil',zoneCalvi:'Depuis Calvi',zonePv:'Depuis Porto-Vecchio',zoneExtra:'Grande excursion',typeBeach:'Plage',typeCulture:'Culture & patrimoine',typeNature:'Nature',places:'lieux',duration:'Sur place',when:'Quand',effort:'Effort',arrival:'Point d’accès',addFav:'Ajouter aux favoris',removeFav:'Retirer des favoris',mapLoading:'Chargement de la carte… Les fiches sont disponibles juste en dessous.',mapUnavailable:'La carte est indisponible pour le moment. Retrouvez tous les lieux ci-dessous et utilisez « Itinéraire » pour les rejoindre.',photoUnavailable:'Photo indisponible',photo:'Source photo',creditsTitle:'Photos et sources',creditsIntro:'Sources des photographies, lieu par lieu. Les photos sont recadrées et compressées pour ce guide. Les auteurs et les droits restent ceux indiqués par chaque source.',updated:'Liens descriptifs contrôlés le 22 septembre 2026. Leur disponibilité peut évoluer.',base:'Point de départ',external:'ouvre un nouvel onglet'},
es:{island:'Córcega',kicker:'Nuestro viaje en familia',hero:'Pueblos en lo alto, calas turquesas, ciudadelas y montañas. Ideas para descubrir Córcega a nuestro ritmo, entre Calvi y Porto-Vecchio.',all:'Todo',beaches:'🏖️ Playas',culture:'🏛️ Cultura',nature:'🌿 Naturaleza',long:'🚗 Excursiones largas',mapTitle:'La isla, al alcance de la mano',mapSub:'Tocá un lugar para ver su ficha. Acercá el mapa para distinguir los lugares cercanos. Los filtros se aplican al mapa y a las ideas de salidas.',mapNote:'🏖️ Playas · 🏛️ Cultura y patrimonio · 🌿 Naturaleza. Los tiempos de viaje son estimaciones de ida, sin paradas. « Cómo llegar » calcula la ruta desde tu punto de partida.',placesTitle:'Para ver, vivir y compartir',placesSub:'Elijan según las ganas del día. Las excursiones largas necesitan un día dedicado; los favoritos quedan guardados en este dispositivo.',favTitle:'❤️ Nuestros favoritos',favEmpty:'Tocá ♡ en una ficha para preparar nuestra selección.',footer:'A fines de septiembre y principios de octubre, adapten las salidas al clima y a los horarios de temporada. Para los barcos, las rutas de montaña y los ríos, consulten la información local antes de salir.',route:'🧭 Cómo llegar',learn:'Descubrir ↗',advice:'💡 Nuestro consejo',zoneCalvi:'Desde Calvi',zonePv:'Desde Porto-Vecchio',zoneExtra:'Excursión larga',typeBeach:'Playa',typeCulture:'Cultura y patrimonio',typeNature:'Naturaleza',places:'lugares',duration:'En el lugar',when:'Cuándo',effort:'Esfuerzo',arrival:'Punto de acceso',addFav:'Agregar a favoritos',removeFav:'Quitar de favoritos',mapLoading:'Cargando el mapa… Las fichas ya están disponibles más abajo.',mapUnavailable:'El mapa no está disponible por el momento. Encontrá todos los lugares más abajo y usá « Cómo llegar » para ir.',photoUnavailable:'Foto no disponible',photo:'Fuente de la foto',creditsTitle:'Fotos y fuentes',creditsIntro:'Fuentes de las fotografías, lugar por lugar. Las fotos están recortadas y comprimidas para esta guía. Los autores y los derechos son los indicados por cada fuente.',updated:'Enlaces descriptivos revisados el 22 de septiembre de 2026. Su disponibilidad puede cambiar.',base:'Punto de partida',external:'abre una pestaña nueva'}
};
const memory={};
function readStore(key){try{return localStorage.getItem(key)??memory[key]??null}catch{return memory[key]??null}}
function writeStore(key,value){memory[key]=value;try{localStorage.setItem(key,value)}catch{/* Memory keeps this session usable in private contexts. */}}
let lang=['fr','es'].includes(readStore('corsicaLang'))?readStore('corsicaLang'):'fr',filter='all',markers=[],map=null,mapReady=false,mapFailed=false;
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const t=k=>UI[lang][k];
const name=p=>lang==='es'?p.name_es:p.name;
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const visible=p=>filter==='all'||p.zone===filter||p.type===filter;
function favs(){try{const a=JSON.parse(readStore('corsicaFav41')||'[]');return Array.isArray(a)?[...new Set(a)].filter(id=>P.some(p=>p.id===id)):[]}catch{return[]}}
function toggleFav(id){let a=favs();a=a.includes(id)?a.filter(x=>x!==id):[...a,id];writeStore('corsicaFav41',JSON.stringify(a));updateFavoriteButtons();renderFavs()}
function updateFavoriteButtons(){const a=favs();document.querySelectorAll('[data-fav]').forEach(b=>{const p=P.find(x=>x.id===b.dataset.fav),on=a.includes(p.id);b.classList.toggle('on',on);b.textContent=on?'♥':'♡';b.setAttribute('aria-pressed',String(on));b.setAttribute('aria-label',(on?t('removeFav'):t('addFav'))+' : '+name(p))})}
function zoneLabel(p){return t(p.zone==='calvi'?'zoneCalvi':p.zone==='pv'?'zonePv':'zoneExtra')}
function typeLabel(p){return t(p.type==='beach'?'typeBeach':p.type==='culture'?'typeCulture':'typeNature')}
function renderCards(){
 const a=P.filter(visible),box=document.getElementById('cards');box.replaceChildren();document.getElementById('count').textContent=a.length+' '+t('places');
 a.forEach(p=>{const c=document.createElement('article');c.className='card '+(p.zone==='extra'?'extra':'');c.id='place-'+p.id;c.tabIndex=-1;
 c.innerHTML=`<div class="photo" data-error="${t('photoUnavailable')}"><img loading="lazy" decoding="async" width="${p.photo_width}" height="${p.photo_height}" src="${p.photo_url}?v=20260922-2" srcset="assets/photos/${p.id}-small.webp?v=20260922-2 ${p.photo_small_width}w, ${p.photo_url}?v=20260922-2 ${p.photo_width}w" sizes="(max-width:760px) calc(100vw - 28px), 570px" alt="${escapeHTML(name(p))}"><span class="tag">${p.emoji} ${typeLabel(p)}</span></div><div class="body"><div class="zone">${zoneLabel(p)}</div><h3>${escapeHTML(name(p))}</h3><div class="meta"><span>🚗 ${escapeHTML(p['drive_'+lang])}</span><span>⏱️ <strong>${t('duration')} :</strong> ${escapeHTML(p['duration_'+lang])}</span><span>🕐 ${escapeHTML(p['when_'+lang])}</span><span>🚶 ${escapeHTML(p['effort_'+lang])}</span></div><p class="desc">${escapeHTML(p[lang])}</p><div class="advice"><b>${t('advice')}</b>${escapeHTML(p['advice_'+lang])}</div><p class="arrival">${t('arrival')} : ${escapeHTML(p.route)}</p><div class="actions"><a class="btn route" href="${escapeHTML(p.route_url)}" target="_blank" rel="noopener noreferrer" aria-label="${escapeHTML(t('route')+' · '+name(p)+' · '+t('external'))}">${t('route')}</a><a class="btn learn" href="${escapeHTML(p.info)}" target="_blank" rel="noopener noreferrer" aria-label="${escapeHTML(t('learn')+' · '+name(p)+' · '+t('external'))}">${t('learn')}</a><button class="btn fav" type="button" data-fav="${p.id}"></button></div></div>`;
 const photo=c.querySelector('img');
 photo.addEventListener('load',()=>{photo.hidden=false;photo.parentElement.classList.remove('photo-missing')});
 photo.addEventListener('error',()=>{
  if(!photo.dataset.retried){photo.dataset.retried='1';photo.removeAttribute('srcset');photo.src=p.photo_url+'?retry='+Date.now();return}
  photo.hidden=true;photo.parentElement.classList.add('photo-missing')
 });
 c.querySelector('[data-fav]').addEventListener('click',()=>toggleFav(p.id));box.append(c)
 });updateFavoriteButtons();
}
function goToPlace(id){const p=P.find(x=>x.id===id);if(!p)return;if(!visible(p))setFilter('all',false);const card=document.getElementById('place-'+id);card?.scrollIntoView({behavior:reducedMotion?'instant':'smooth',block:'start'});card?.focus({preventScroll:true})}
function renderFavs(){const ids=favs(),b=document.getElementById('favlist');b.replaceChildren();document.getElementById('favempty').hidden=ids.length>0;ids.forEach(id=>{const p=P.find(x=>x.id===id),x=document.createElement('button');x.type='button';x.textContent=p.emoji+' '+name(p);x.addEventListener('click',()=>goToPlace(id));b.append(x)})}
function renderCredits(){const b=document.getElementById('photoCredits');b.replaceChildren();P.forEach(p=>{const row=document.createElement('p'),a=document.createElement('a');a.href=p.photo_source;a.target='_blank';a.rel='noopener noreferrer';a.textContent=p.photo_credit;row.append(name(p)+' — ',a);if(p.photo_license){const license=document.createElement('a');license.href=p.photo_license_url;license.target='_blank';license.rel='noopener noreferrer';license.textContent=p.photo_license;row.append(' · ',license)}b.append(row)})}
function drawMarkers(){if(!map||!mapReady)return;markers.forEach(m=>m.remove());markers=[];P.filter(visible).forEach(p=>{const e=document.createElement('button');e.type='button';e.className='marker '+p.type;e.textContent=p.emoji;e.title=name(p);e.setAttribute('aria-label',name(p));e.addEventListener('click',()=>goToPlace(p.id));markers.push(new maplibregl.Marker({element:e}).setLngLat([p.lng,p.lat]).addTo(map))})}
function fitMap(){if(!map||!mapReady)return;const a=P.filter(visible);if(!a.length)return;const bounds=new maplibregl.LngLatBounds();a.forEach(p=>bounds.extend([p.lng,p.lat]));map.fitBounds(bounds,{padding:55,maxZoom:10,duration:reducedMotion?0:650})}
function setFilter(next,moveMap=true){filter=next;document.querySelectorAll('.chip').forEach(b=>{const on=b.dataset.f===filter;b.classList.toggle('on',on);b.setAttribute('aria-pressed',String(on))});renderCards();renderFavs();drawMarkers();if(moveMap)fitMap()}
function applyLang(){document.documentElement.lang=lang;document.title=lang==='fr'?'Corse 2026 · Notre guide en famille':'Córcega 2026 · Nuestra guía en familia';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));['fr','es'].forEach(l=>{const b=document.getElementById(l+'Btn');b.classList.toggle('on',lang===l);b.setAttribute('aria-pressed',String(lang===l))});document.getElementById('langPill').textContent=lang==='fr'?'🇫🇷 Français':'🇦🇷 Español';writeStore('corsicaLang',lang);renderCards();renderFavs();renderCredits();drawMarkers();if(mapFailed)showMapFailure()}
function showMapFailure(){mapFailed=true;const b=document.getElementById('map');b.classList.add('map-failed');b.replaceChildren();const p=document.createElement('p');p.className='map-status';p.textContent=t('mapUnavailable');b.append(p)}
function initMap(){
 try{
  if(!window.maplibregl){showMapFailure();return}
  document.getElementById('map').replaceChildren();
  map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/liberty',center:[8.98,42.08],zoom:7.2});
  map.addControl(new maplibregl.NavigationControl({showCompass:false}),'top-right');
  const timeout=setTimeout(()=>{if(!mapReady){map?.remove();map=null;showMapFailure()}},45000);
  map.on('style.load',()=>{clearTimeout(timeout);mapReady=true;drawMarkers();fitMap()});
  map.on('error',()=>{/* Tile errors may recover; the initial-load timeout handles total failure. */});
 }catch{map=null;showMapFailure()}
}
document.getElementById('frBtn').addEventListener('click',()=>{lang='fr';applyLang()});document.getElementById('esBtn').addEventListener('click',()=>{lang='es';applyLang()});
document.querySelectorAll('.chip').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.f==='all'));b.addEventListener('click',()=>setFilter(b.dataset.f))});
applyLang();
// The guide renders before the map dependency is downloaded.
const mapScript=document.createElement('script');mapScript.src='assets/vendor/maplibre-gl.js';mapScript.onload=initMap;mapScript.onerror=showMapFailure;document.body.append(mapScript);
